apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}-deployment
  sessionAffinity: None
status:
  loadBalancer: {}