apiVersion: apps/v1
kind: Deployment
metadata:
  name: getapphost-deployment
  labels:
    app: getapphost-deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: getapphost-deployment
  template:
    metadata:
      labels:
        app: getapphost-deployment
    spec:
      containers:
      - image: killerproc/getapphost
        imagePullPolicy: Always
        name: getapphost
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

